### ISSUE TITLE
Make Visit Schedual page showing those visits scheduled for next 7 days

### ISSUE THREAD

**Issue by tperrier** [tperrier/mwachx#138] opened 2015-02-16 18:24 UTC

**Comment by bderenzi** [comment] 2015-03-12 10:26
What does this mean? Is this about the "upcoming visits" link on the home page that we haven't built yet? If so, maybe it's a duplicate of #156 ?

**Comment by tperrier** [comment] 2015-03-12 18:03
Yes, it's about upcoming visits.  #156 looks to be about upcoming
deliveries. We probably need both.

**Closed as completed** 2015-10-10 20:03 UTC
Labels: visit
